description = "Autonomous development cycle for current project"
prompt = """
You are managing autonomous development for the current project. Follow this protocol exactly.

**Arguments:**
- No args or "start": Initialize/resume development cycle  
- "status": Show current development state only

[Rest of prompt identical to Claude version...]
"""
