name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
    - name: Run shellcheck
      run: |
        if ls lib/*.sh 1> /dev/null 2>&1; then shellcheck lib/*.sh; fi
        if ls bin/* 1> /dev/null 2>&1; then shellcheck bin/*; fi
        if [ -f install.sh ]; then shellcheck install.sh; fi
        if [ -f uninstall.sh ]; then shellcheck uninstall.sh; fi